account/urls.py
from django.urls import path
from .views import registerView
from .import views

app_name = 'account'

urlpatterns = [
    
    path('signup/', registerView, name='signup'),
    path('<pk>/update', views.UserEditView.as_view(), name='edit_profile')
]

blog/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from.views import displayTime, displayContact, MyViews, book_list, Post_list, post_detail, loginView, contactview
from .import views

app_name = 'blog'

urlpatterns = [
    path("books_list/" , book_list),
    path("", Post_list),
    path("contact/", displayContact, name="contact"),
    path("about/", contactview, name="about"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('login/', views.loginView, name="login"),
    path('profile/', views.profileView, name='profile'),
    path("logout/", views.logout_view, name='logout'),
    path('home/', MyViews.as_view, name="home")

]

introtodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("ecom/", include("ecommerce.urls")),
    path("account/", include("account.urls"))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from turtle import title
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    isbn = models.CharField(max_length=13)

    def __str__(self):
        return self.title

    

# Blog Model 
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published')
        )
    title = models.CharField(max_length=250)
    post_image = models.ImageField(blank=True, null=True)
    slug = models.CharField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated =models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


    

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

# class ContactForm(forms.Forms):
#     name=forms.CharField(max_length=50, label='Name')
#     surname=forms.CharField(max_length=50, label='Surname')
#     email=forms.EmailField(max_length=50, label='Email')
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
import datetime
from django.views.generic import TemplateView
from.models import Book, Post, Comment
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from .forms import CommentForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def displayTime(request):
    now = datetime.datetime.now()
    html ="Time is{}".format(now)
    return HttpResponse(html)

def displayContact(request):
    return render(request, "contact.html", {})

class MyViews(TemplateView):
    template_name = "index.html"
    
def book_list(request):
    books = Book.objects.all()
    return render(request, "book_list.html", {"books" : books} )

#view for all posts
def Post_list(request):
    object_lists = Post.objects.all()
    paginator = Paginator(object_lists, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "index.html", {"page" : page, "posts" : posts})

#View for single post
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method== 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm() 
    return render(request, 'post_detail.html',{'post':post,'comments':comments, 'new_comment': new_comment ,'comment_form':comment_form})

def loginView(request):
    if request.method== 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'You have succesfuly logged in as {username}')
                return redirect ('blog:profile')
            else:
                messages.error(request, f'Invalid username or password.')
        else:
            messages.error(request, f'Invalid username or password.')
    form = AuthenticationForm()
    return render (request, 'authenticate/login.html',{'form':form})

@login_required(login_url='blog:login')
def profileView(request):
    return render(request, 'profile.html', {})

def logout_view(request):
    logout(request)
    return redirect('/')

def contactview(request):
    return render(request, "about.html", {})

blog/templates/about.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="about-section">
    <h1>About Us Page</h1>
    <p>Welcome!</p>
    <p>You have come to the right place,here you will see list of our  team, people that  have built this business from the ground up and are still working hard even today to continue making it  a success.</p>
  </div>
  
  <h2 style="text-align:center">Our Team</h2>
  <div class="row">
    <div class="column">
      <div class="card">
        <img src="{% static 'images/1_LPPpUZLved9uY_9gvRgRlw.jpeg'  %}" alt="Londi" style="width:25%">
        <div class="container">
          <h2>Londi Mahlangu</h2>
          <p class="title">CEO & Founder</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>londimahlangu29@gmail.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="{% static 'images/download.jpg' %}" alt="Nkanyezi" style="width:25%">
        <div class="container">
          <h2>Nkanyezi Mahlangu</h2>
          <p class="title">Art Director</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>nkanyezi2@yahoo.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="{% static 'images/7c4438f45f4356f02d938a9b5ad14e67.jpg' %}" alt="Wendy" style="width:25%">
        <div class="container">
          <h2>Wendy Mahlangu</h2>
          <p class="title">Designer</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>wendy@hotmail.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/mobile.css' %}">
    

</head>
<body>
    <nav>
        <div class="logo">
            <h1>Fashion Blog</h1>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'blog:home' %}">Home</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
            <li><a href="{% url 'blog:contact' %}">Contact</a></li>
            <li><a href="">Blog </a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog:logout' %}">logout </a></li>
            {% else %}
            <li class="nav-ltem"><a href="{% url 'blog:login' %}" class="nav-links">Login</a></li>
            <li>
                <a href="{% url 'account:signup' %}">SignUp</a>
            </li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li>Hello {{request.user}}</li>
            {% endif %}
        </ul>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>

    <div class="container mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-alert mt-5 " role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    </div>

    {% block content %}

    {% endblock content %}
    
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/app.js' %}"></script> 
</html>

blog/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book List</title>
</head>
<body>
    <h1>This Is My Book List</h1>
    {%for book in books%}
    <ul>
        <li>Title: {{book.title}}</li>
        <li>Subtitle: {{book.subtitle}}</li>
        <li>Author: {{book.author}}</li>
        <li>ISBN: {{book.isbn}}</li>


    </ul>
    {%endfor%}
</body>
</html>

blog/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div style="text-align:center">
      <h2>Contact Us</h2>
      <p>Swing by for a cup of coffee, or leave us a message:</p>
    </div>
    <div class="row">
      <div class="column">
        <img src="{% static 'images/images.jpg' %}" style="width:100%">
      </div>
      <div class="column">
        <li>
        <form action="/action_page.php">
          <label for="fname">First Name</label>
          <input type="text" id="fname" name="firstname" placeholder="Your name..">
          <label for="lname">Last Name</label>
          <input type="text" id="lname" name="lastname" placeholder="Your last name..">
          <label for="country">Country</label>
          <select id="country" name="country">
            <option value="australia">South Africa</option>
            <option value="canada">Europe</option>
            <option value="usa">USA</option>
          </select>
          <label for="subject">Subject</label>
          <textarea id="subject" name="subject" placeholder="Write something.." style="height:170px"></textarea>
          <input type="submit" value="Submit">
        </form>
      </li>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/home.html
{% extends "base.html" %}
{% block content %}

<p>THis is my home page</p>

{% endblock %}

blog/templates/index.html
{% extends "base.html" %}
{% block content %}

    {% load static %}
    <section class="heroSection">
        <div class="main">
            <h1 class="sectionTitle">Liter your hearts <br> and minds</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore vitae ducimus, totam obcaecati consectetur amet aliquam voluptatibus sapiente dolores minus. Consequatur quia aspernatur veniam voluptatibus placeat. Maxime quaerat debitis cum.</p>
            <button class="hero"><a href="#">Learn More</a></button>
        </div>
    </section>

    
    {% for post in posts %}
   
 <h1>This Is My Post List</h1>
        <h2>
            <a href="{{ post.get_absolute_url }}">
            {{post.title}}
            
        </a>  
        </h2>
        {% if post.post_image %}
                <img src="{{ post.post_image.url }}" alt="">
        {% endif %}
        <p class="date">
        Published {{post.author}} by {{post.author}}</p>
        
        {{post.slug}}
        
        <p>{{post.body|truncatewords:30|linebreaks}}</p>
        
        {{post.publish}}

    {% endfor %}

    {% include "pagination.html" with page=posts %}

    {% endblock %}

 

</body>
</html>

blog/templates/pagination.html
<div class="pagination container justify-content-center">
  <ul class="pagination">
    <li class="page-items">
      {% if page.has_previous %}
     <a href="?page={{ page.previous_page_number }}" class="page=link">Previous</a>
      {% endif %}
    </li>

    <li class="page-item page-link">
      Page {{ page.number }}
    </li>

    <li class="page-item page-link"> of </li>
    <li class="page-item page-link"> page 1 of 2 </li>
    <li class="page-item">
      {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}" class="page-link">Next</a>
      {% endif %}

    </li>

  </ul>
    

</div>

blog/templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}

<!-- comment -->
<div class="container">
<!--  display number of comment-->
  <body>
    <h1> {{post.title}} </h1>

    <p class="date">
    Published {{ post.author }} by {{ post.author }}</p>
    
    <p>{{ post.body|linebreaks }}</p>
    
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment {{ total_comments|pluralize }}
    </h2>
    {% endwith %}

    {% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>

    {% empty %}
     <p>There are no comments</p>
    {% endfor %}

    {% if new_comment %}
      <h2>Your comment has been added</h2>
    {% else %}
      <h2>Add a new comment</h2>

      <form method="POST">
        {{ comment_form|crispy }}
        {% csrf_token %}

      <p><input type="submit" value="Add comment"></p>
      </form>
    {% endif %}
</div>
  
{% endblock %}

blog/templates/profile.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'account:editprofile' user.id">edit your profile</a>


{% endblock %}